services:
- type: web
  name: fastapi-app
  env: docker
  buildCommand: "" # Docker build commands are often not needed as Render uses the Dockerfile
  startCommand: "" # Docker start commands are often not needed as Render uses the Dockerfile's CMD
  dockerfilePath: ./Dockerfile # Path to your Dockerfile
  envVars:
    - key: RABBITMQ_URL
      value: amqp://rabbitmq:rabbitmq@rabbitmq:5672/  # Updated username to match the RABBITMQ_DEFAULT_USER

- type: web # Note: RabbitMQ is also accessible as a web service if management UI is needed
  name: rabbitmq
  env: docker
  image: rabbitmq:3-management
  envVars:
    - key: RABBITMQ_ERLANG_COOKIE
      generateValue: true
    - key: RABBITMQ_DEFAULT_USER
      value: rabbitmq
    - key: RABBITMQ_DEFAULT_PASS
      generateValue: true
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq
    sizeGB: 10
  ports:
    - port: 15672 # Management interface
      service: private # Set to 'public' if external access is needed, 'private' for internal
    - port: 5672 # AMQP port, no need to explicitly expose it unless external access is required
      service: private
