FROM python:3.11-slim

WORKDIR /app

# Copy only requirements.txt first to leverage Docker cache
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

CMD ["uvicorn", "api.endpoints:app", "--host", "0.0.0.0", "--port", "8000", "--root-path", "/trading/api"]