FROM node:20.12.2

WORKDIR /app

# Copy package.json and yarn.lock (if you're using Yarn)
COPY package.json yarn.lock* ./
RUN yarn install

# Copy the rest of your app's source code
COPY . .

EXPOSE 3000

CMD ["yarn", "dev", "--host", "0.0.0.0"]