FROM node:20.12.2

WORKDIR /app

# Copy all files
COPY . .

# Install Firebase CLI and inotify-tools
RUN apt-get update && apt-get install -y inotify-tools
RUN npm install -g firebase-tools

# Install dependencies
RUN yarn install

# Make the firebase-dev.sh script executable
RUN chmod +x firebase-dev.sh

# Serve the app
CMD ["./firebase-dev.sh"]