FROM python:3.11-slim

WORKDIR /app

# Copy all files, including secrets
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "api.endpoints:app", "--host", "0.0.0.0", "--port", "8000", "--root-path", "/trading_api"]