MD_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoidmVudm9vb28uZ21haWwuY29tIiwiZW1haWwiOiJ2ZW52b29vb0BnbWFpbC5jb20iLCJ1c2VySWQiOiI4NjIyNzk3YS05ZDkzLTQ0MTYtYjhlNy0wNTdiMDFkNjc1NjEiLCJpYXQiOjE3MDYwNTk3MjgsImV4cCI6MTczNzYxNzMyOH0.QhvzD9nk5C3L-28u5gfZXqJosOvIpV-S6ElKwp5HeU4"

TABLE_REF: "session_parameter"
TABLE_RES: "trading_data"
DATASET: "trader"
DATA_FILE: "analysis/results/new_run_data.parquet"
DATA_DIR: "analysis/results"

MONGODB_HOST: "localhost"
MONGODB_PORT: 27017
COLLECTION_NAME: "message"

ROLLING_WINDOW_SIZE: 3

NUM_SERVERS: 10
UVICORN_STARTING_PORT: 8000

TYPE_MAPPING:
  ADD_ORDER: 1
  CANCELLATION_PARTIAL: 2
  CANCEL_ORDER: 3
  EXECUTION_VISIBLE: 4
  EXECUTION_HIDDEN: 5
  CROSS_TRADE: 6
  TRADING_HALT: 7

MESSAGE_COLUMNS: ['trading_session_id', 'Time', 'Event Type', 'Order ID', 'Trader ID', 'Size', 'Price', 'Direction']
LOBSTER_BOOK_COLUMN: 'LOBSTER_BOOK'


# when all tuple, treat as sobol, (2p+2) * 2 ^ p will be run 
BOUNDS:
  trade_intensity_informed:  !python/tuple [0.05, 0.3]
  passive_order_probability: !python/tuple [0.5, 0.9]

RESOLUTION: 1 # does not matter if not tuple



# when all list, treat as permutation, all combinations will be run
# BOUNDS:
#   trade_intensity_informed:  [0.05, 0.3]
#   passive_order_probability: [0.5, 0.9]
#   trading_day_duration: [1,2]