import json
import time
import uuid
from pathlib import Path
from typing import Dict, Optional, Tuple

# In-memory storage for lab tokens
LAB_TOKENS: Dict[str, dict] = {}

# File-based persistence (hedge against server restart)
_LAB_TOKENS_FILE = Path(__file__).parent.parent / "logs" / "lab_tokens.json"


def _persist_tokens():
    try:
        _LAB_TOKENS_FILE.parent.mkdir(parents=True, exist_ok=True)
        serializable = {}
        for token, data in LAB_TOKENS.items():
            serializable[token] = {
                "participant_index": data["participant_index"],
                "treatment_group": data.get("treatment_group"),
                "created_at": data["created_at"],
                "used": data["used"],
            }
        with open(_LAB_TOKENS_FILE, "w") as f:
            json.dump(serializable, f, indent=2)
    except Exception as e:
        print(f"Warning: failed to persist lab tokens: {e}")


def _load_tokens():
    global LAB_TOKENS
    try:
        if _LAB_TOKENS_FILE.exists():
            with open(_LAB_TOKENS_FILE, "r") as f:
                data = json.load(f)
            for token, info in data.items():
                if token not in LAB_TOKENS:
                    LAB_TOKENS[token] = info
    except Exception as e:
        print(f"Warning: failed to load lab tokens: {e}")


# Load any persisted tokens on module import
_load_tokens()


def generate_lab_tokens(count: int, base_url: str = "", num_treatments: int = 1) -> list:
    """Generate lab tokens, distributing evenly across treatment groups.

    If num_treatments > 1, tokens are assigned treatment_group 0..N-1 in round-robin.
    E.g. count=100, num_treatments=4 → 25 tokens per treatment group.
    """
    links = []
    for i in range(count):
        token = f"lab_{uuid.uuid4().hex}"
        treatment_group = i % num_treatments if num_treatments > 1 else None
        LAB_TOKENS[token] = {
            "participant_index": i + 1,
            "treatment_group": treatment_group,
            "created_at": time.time(),
            "used": False,
        }
        if base_url:
            links.append(f"{base_url}?LAB_TOKEN={token}")
        else:
            links.append(token)
    _persist_tokens()
    return links


def validate_lab_token(token: str) -> Tuple[bool, Optional[dict]]:
    if token not in LAB_TOKENS:
        # Try reloading from file in case tokens were generated by another process
        _load_tokens()
    if token not in LAB_TOKENS:
        return False, None

    info = LAB_TOKENS[token]

    # Mark as used on first validation
    if not info["used"]:
        info["used"] = True
        _persist_tokens()

    participant_index = info["participant_index"]
    trader_id = f"HUMAN_LAB_{participant_index}"

    treatment_group = info.get("treatment_group")
    user = {
        "uid": f"lab_{participant_index}",
        "email": f"lab_{participant_index}@lab.local",
        "gmail_username": f"LAB_{participant_index}",
        "is_admin": False,
        "is_lab": True,
        "lab_token": token,
        "trader_id": trader_id,
        "treatment_group": treatment_group,
    }
    return True, user


# Global mapping of lab trader_ids to user data (populated on login)
lab_trader_map: Dict[str, dict] = {}
