MD_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoidmVudm9vb28uZ21haWwuY29tIiwiZW1haWwiOiJ2ZW52b29vb0BnbWFpbC5jb20iLCJ1c2VySWQiOiI4NjIyNzk3YS05ZDkzLTQ0MTYtYjhlNy0wNTdiMDFkNjc1NjEiLCJpYXQiOjE3MDYwNTk3MjgsImV4cCI6MTczNzYxNzMyOH0.QhvzD9nk5C3L-28u5gfZXqJosOvIpV-S6ElKwp5HeU4"

TABLE_REF: "session_parameter"
TABLE_RES: "trading_data"
DATASET: "trader"
DATA_FILE: "analysis/results/new_run_data.parquet"
DATA_DIR: "analysis/results"

NUM_SERVERS: 10
UVICORN_STARTING_PORT: 8000

TYPE_MAPPING:
  ## at the moment, the update type within the simulation is too broad, 
  ## we need to split it into multiple types
  update: 1  # Submission of a new limit order
  cancel: 2  # Cancellation (partial deletion of a limit order)
  delete: 3  # Deletion (total deletion of a limit order)
  execute_visible: 4  # Execution of a visible limit order
  execute_hidden: 5  # Execution of a hidden limit order
  cross_trade: 6  # Indicates a cross trade, e.g., auction trade
  stop_trading: 7  # Trading halt indicator


MESSAGE_COLUMNS: ['trading_session_id','Time', 'Event Type', 'Order ID', 'Trader ID','Size', 'Price', 'Direction']
LOBSTER_BOOK_COLUMN: 'LOBSTER_BOOK'